config/routes.rb
Rails.application.routes.draw do
  get 'about/index'

  get 'contact/index'

  root 'contact#index'
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options={})
    { locale: (I18n.locale != I18n.default_locale ? I18n.locale : nil) }
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/about/index.html.slim
h1 = t('about')
.standout
  = t('about_html')
  h3 class="center" = mail_to 'agrohandel@gmail.com', t('cooperation')

app/views/contact/index.html.slim
h1 = t('contact')
.fotorama data-autoplay="true" data-loop="true"
  = image_tag 'spichrz.jpg'
  = image_tag 'wallpaper-814010.jpg'
  = image_tag 'wallpaper-106400.jpg'
  = image_tag 'wallpaper-183114.jpg'
  = image_tag 'wallpaper-364799.jpg'
.standout
  div(itemtype="http://schema.org/Organization" itemscope)
    span itemprop="name" Agro-Handel sp.j. Skibińska, Wieczorek
    div(itemprop="address" itemtype="http://schema.org/PostalAddress" itemscope)
      span itemprop="streetAddress" Spichrzowa 2
      br
      span itemprop="postalCode" 62-045
      span>
      span itemprop="addressLocality" Pniewy
    span> tel.
    span itemprop="telephone" 61-291-17-16
    br
    = mail_to 'agrohandel@gmail.com', nil, {itemprop: 'email'}
  time itemprop="openingHours" datetime="Mo-Fr 8:00-15:00" = t('opening_hours')
div style="overflow: hidden; height: 500px; width: inherit;"
  div id="gmap_canvas" style="height: 500px; width: inherit;"

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar
  .container
    .navbar-header
      span class="navbar-brand" &nbsp;
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
= link_to t('contact'), contact_index_path, {class: 'navbar-brand', id: 'contact'}
= link_to t('about'), about_index_path, {class: 'navbar-brand', id: 'about'}

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Agro-Handel'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Agro-Handel'}"
    script src="http://maps.google.com/maps/api/js?sensor=false" data-turbolinks-track=true
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    link href="http://cdnjs.cloudflare.com/ajax/libs/fotorama/4.5.1/fotorama.css" rel="stylesheet" data-turbolinks-track=true
    script src="http://cdnjs.cloudflare.com/ajax/libs/fotorama/4.5.1/fotorama.js" data-turbolinks-track=true
    == csrf_meta_tags
    = render 'layouts/ga'
  body data-controller="#{params[:controller]}"
    div class="row"
      div class="col-sm-3"
      div class="col-sm-6"
        div class="row"
          div class="col-xs-3"
          div class="col-xs-6"
            = image_tag 'logo.png', alt: 'Agro-Handel'
            h1 class="logo" Agro-Handel
            h1 class="logo" Pniewy
          div class="col-xs-3"
            a href="#{request.path}"
              = image_tag 'Flag_of_Poland.png', class: 'flag'
            a href="#{request.path + '?locale=en'}"
              = image_tag 'Flag_of_the_United_Kingdom.png', class: 'flag'
        header
          == render 'layouts/navigation'
        main[role="main"]
          == render 'layouts/messages'
          == yield
        hr
        footer
          = mail_to 'wieczorek1990@gmail.com', '&copy; łw'.html_safe
      div class="col-sm-3"